
import com.sun.tools.javac.Main;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Motasem
 */
public class YildizKhouliGameSecoundMap extends javax.swing.JFrame {
    YildizKhouliDblLinkedList<JButton> buttons = new YildizKhouliDblLinkedList<>();
    YildizKhouliDblLinkedList<String> map = new YildizKhouliDblLinkedList<>();
      int size = 35;
      int score = 0;
      String playersName;
      String temp = "Start";
        
    
    
    /**
     * Creates new form GameSecoundMap
     */
    public YildizKhouliGameSecoundMap() {

        initComponents();
        Random rand = new Random();
        buttons.add(jButton3);
        buttons.add(jButton4);
        buttons.add(jButton5);
        buttons.add(jButton6);
        buttons.add(jButton7);
        buttons.add(jButton8);
        buttons.add(jButton9);
        buttons.add(jButton10);
        buttons.add(jButton11);
        buttons.add(jButton12);
        buttons.add(jButton13);
        buttons.add(jButton14);
        buttons.add(jButton15);
        buttons.add(jButton16);
        buttons.add(jButton17);
        buttons.add(jButton18);
        buttons.add(jButton19);
        buttons.add(jButton20);
        buttons.add(jButton21);
        buttons.add(jButton22);
        buttons.add(jButton23);
        buttons.add(jButton24);
        buttons.add(jButton25);
        buttons.add(jButton26);
        buttons.add(jButton27);
        buttons.add(jButton28);
        buttons.add(jButton29);
        buttons.add(jButton30);
        buttons.add(jButton31);
        buttons.add(jButton32);
        buttons.add(jButton33);
        buttons.add(jButton34);
        buttons.add(jButton35);
        buttons.add(jButton36);
        buttons.add(jButton37);
        
        jPanel1.setBackground(new Color(180, 220, 255));
        
         for (int i = 0; i < size; i++) {
            map.add(buttons.getCurrent().getText());
            map.moveForward(1);
        }
         map.reset();
         int counter = 0;
         for (int i = 0; i < size; i++) {
            int number = rand.nextInt(100);
            String text;
             if (number > 50) {
                 text = "  Empty  ";
             }else if ( 30 < number && number < 50) {
                 text = "   +10   ";
             }else if (10 < number && number < 30) {
                 text = "   -5   ";
             }else if (5 < number && number < 10) {
                 text = "ladder +5";
             }else if (0 < number && number < 5) {
                 if (counter < 7 || counter > 27) {
                     text = "  Empty  ";
                   
                 }else text = "ladder -5";

             }else{
                 text = "  Empty  ";
             }
             jButton3.setText("X \nStart");
             
             buttons.getCurrent().setBackground(text == "   +10   " ? Color.YELLOW : (text == "   -5   " ? Color.RED : Color.WHITE)); 
             jButton3.setBackground(Color.PINK);

             buttons.getCurrent().setText(text);
             map.setCurrent(text);
             
             buttons.moveForward(1);
             map.moveForward(1);

        }
         buttons.reset();
         map.reset();
                     

         playersName = YildizKhouliGameFirstMap.playerName;
         jLabelPlayersName.setText(playersName);
         
         jLabelScore.setText(String.valueOf(score));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jButton37 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabelDice = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButtonRoll = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelScore = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelPlayersName = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jButton37.setText("jButton37");

        jButton19.setText("jButton19");

        jButton20.setText("jButton20");

        jButton21.setText("jButton21");

        jLabelDice.setText("0");

        jButton3.setText("Start");
        jButton3.setMaximumSize(new java.awt.Dimension(81, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(81, 23));

        jButton22.setText("jButton22");

        jButton4.setText("jButton4");
        jButton4.setMaximumSize(new java.awt.Dimension(81, 23));
        jButton4.setMinimumSize(new java.awt.Dimension(81, 23));

        jButton23.setText("jButton23");

        jButton5.setText("jButton5");
        jButton5.setMaximumSize(new java.awt.Dimension(81, 23));
        jButton5.setMinimumSize(new java.awt.Dimension(81, 23));

        jButton24.setText("jButton24");

        jButton6.setText("jButton6");
        jButton6.setMaximumSize(new java.awt.Dimension(81, 23));
        jButton6.setMinimumSize(new java.awt.Dimension(81, 23));

        jButton25.setText("jButton25");

        jButton7.setText("jButton7");
        jButton7.setMaximumSize(new java.awt.Dimension(81, 23));
        jButton7.setMinimumSize(new java.awt.Dimension(81, 23));

        jButton26.setText("jButton26");

        jButton8.setText("jButton8");
        jButton8.setMaximumSize(new java.awt.Dimension(81, 23));
        jButton8.setMinimumSize(new java.awt.Dimension(81, 23));

        jButton27.setText("jButton27");

        jButton28.setText("jButton28");

        jButton9.setText("jButton9");
        jButton9.setMaximumSize(new java.awt.Dimension(81, 23));
        jButton9.setMinimumSize(new java.awt.Dimension(81, 23));

        jButton29.setText("jButton29");

        jButton10.setText("jButton10");

        jButton30.setText("jButton30");

        jButton11.setText("jButton11");

        jButton31.setText("jButton31");

        jButton12.setText("jButton12");

        jButton32.setText("jButton32");

        jButton13.setText("jButton13");

        jButton33.setText("jButton33");

        jButton14.setText("jButton14");

        jButton34.setText("jButton34");

        jButton15.setText("jButton15");

        jButton35.setText("jButton35");

        jButton16.setText("jButton16");

        jButton36.setText("jButton36");

        jButton17.setText("jButton17");

        jButton18.setText("jButton18");

        jButtonRoll.setText("Roll ");
        jButtonRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRollActionPerformed(evt);
            }
        });

        jLabel1.setText("Sore:");

        jLabelScore.setText("jLabel2");

        jLabel3.setBackground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Player's name:");

        jLabelPlayersName.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton29, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(65, 65, 65)
                                            .addComponent(jButton21)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton22)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton23)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButton24)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton25)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton26)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton27)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton28))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(63, 63, 63)
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton10))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addComponent(jButton19)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton18)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton17)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton16)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton15)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton14)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton13)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton12))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(64, 64, 64)
                                            .addComponent(jButton37)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButton36)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButton35)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton34)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton33)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton32)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton31)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton30)))
                                    .addComponent(jButton20))
                                .addGap(13, 13, 13))
                            .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(145, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addComponent(jButtonRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelDice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelScore)
                            .addComponent(jLabelPlayersName, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(130, 130, 130))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelPlayersName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRoll)
                    .addComponent(jLabelDice)
                    .addComponent(jLabel1)
                    .addComponent(jLabelScore))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRollActionPerformed
        // TODO add your handling code here:
        jButton3.setText("Start");
        buttons.getCurrent().setText(temp);
        int dice = (int)(Math.random() * 6) +1;
        jLabelDice.setText(String.valueOf(dice));
        
         for (int i = 0; i < dice; i++) {
            if (!buttons.isAtEnd()) {
                buttons.moveForward(1);
                map.moveForward(1);
            } else {
                break;
            }
        }
        
        boolean bool = true;
       while (bool) {
            String currentText = buttons.getCurrent().getText();
            switch (currentText.trim()) {
                case "Empty":
                    temp = map.getCurrent();
                    buttons.getCurrent().setText("    X    ");
                    bool = false;
                    break;
                case "+10":
                    temp = map.getCurrent();
                    buttons.getCurrent().setText("    X    ");
                    score += 10;
                    bool = false;
                    break;
                case "-5":
                    temp = map.getCurrent();
                    buttons.getCurrent().setText("    X    ");
                    score -= 5;
                    bool = false;
                    break;
                case "ladder +5":
                    temp = map.getCurrent();
                    for (int i = 0; i < 5 && !buttons.isAtEnd(); i++) {
                        buttons.moveForward(1);
                        map.moveForward(1);
                    }
                    temp = map.getCurrent();
                    buttons.getCurrent().setText("    X    ");
                    bool = false;
                    break;
                case "ladder -5":
                    temp = map.getCurrent();
                    for (int i = 0; i < 5 && !buttons.isAtStart(); i++) {
                        buttons.moveBackward(1);
                        map.moveBackward(1);
                    }
                    temp = map.getCurrent();
                    buttons.getCurrent().setText("    X    ");
                    bool = false;
                    break;
                default:
                    temp = "  Empty  ";
                    buttons.getCurrent().setText("    X    ");
                    bool = false;
            }
                    jLabelScore.setText(String.valueOf(score));

        }
        if (buttons.isAtEnd()) {
            JOptionPane.showMessageDialog(null,"You finished the game");
            try {
                    BufferedWriter writer = new BufferedWriter(
                            new FileWriter("score.txt", true)
                    );
                    writer.write(jLabelPlayersName.getText() + ", Level2," + score);

                    writer.newLine();
                    writer.close();
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Error writing to file: " + e.getMessage());
                }
            YildizKhouliMainMenu x = new YildizKhouliMainMenu();
            x.setVisible(true); 
            this.dispose();
        }
        
        
        
        
        
    }//GEN-LAST:event_jButtonRollActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YildizKhouliGameSecoundMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YildizKhouliGameSecoundMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YildizKhouliGameSecoundMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YildizKhouliGameSecoundMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YildizKhouliGameSecoundMap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonRoll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDice;
    private javax.swing.JLabel jLabelPlayersName;
    private javax.swing.JLabel jLabelScore;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
