
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.util.Random;
import javax.swing.JTextArea;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Motasem
 */
public class YildizKhouliGameFirstMap extends javax.swing.JFrame {

    YildizKhouliLinkedList<String> map = new YildizKhouliLinkedList<>();

    YildizKhouliLinkedList<JTextArea> textAreas = new YildizKhouliLinkedList<>();

    int score;
    public static String playerName;

    /**
     * Creates new form GameFirstMap
     */
    public YildizKhouliGameFirstMap() { // map 1in generate asamasi burda gerceklestiriyor (randomly)
        
     initComponents();
        score = 0;
        
        textAreas.AddFirst(A1);
        textAreas.AddLast(A2);
        textAreas.AddLast(A3);
        textAreas.AddLast(A4);
        textAreas.AddLast(A5);
        textAreas.AddLast(A6);
        textAreas.AddLast(A7);
        textAreas.AddLast(A8);
        textAreas.AddLast(A9);
        textAreas.AddLast(A10);
        textAreas.AddLast(A11);
        textAreas.AddLast(A12);
        textAreas.AddLast(A13);
        textAreas.AddLast(A14);
        textAreas.AddLast(A15);
        textAreas.AddLast(A16);
        textAreas.AddLast(A17);
        textAreas.AddLast(A18);
        textAreas.AddLast(A19);
        textAreas.AddLast(A20);
        textAreas.AddLast(A21);
        textAreas.AddLast(A22);
        textAreas.AddLast(A23);
        textAreas.AddLast(A24);
        textAreas.AddLast(A25);
        textAreas.AddLast(A26);
        textAreas.AddLast(A27);
        textAreas.AddLast(A28);
        textAreas.AddLast(A29);
        textAreas.AddLast(A30);
        textAreas.AddLast(A31);
        textAreas.AddLast(A32);

        
        textAreas.get(0).setText("START");
    textAreas.get(0).setBackground(Color.MAGENTA);

    textAreas.get(textAreas.size() - 1).setText("END");
    textAreas.get(textAreas.size() - 1).setBackground(Color.MAGENTA);

    
    for (int i = 1; i < textAreas.size() - 1; i++) {
        int random = (int) (Math.random() * 3);

        if (random == 0) {
            textAreas.get(i).setText("+10");
            textAreas.get(i).setBackground(Color.GREEN);
        } else if (random == 1) {
            textAreas.get(i).setText("EMPTY");
            textAreas.get(i).setBackground(Color.CYAN);
        } else if (random == 2) {
            textAreas.get(i).setText("TRAP");
            textAreas.get(i).setBackground(Color.ORANGE);
        }
    }

    
    for (int i = 0; i < textAreas.size(); i++) {
        map.AddLast(textAreas.get(i).getText());
    }


    }

    int GenerateRandomNumber() { // 1 ile 6 arasi random bir sayi don.
        Random rand = new Random();
        int randomNumber = rand.nextInt(6) + 1;

        return randomNumber;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        A2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        A3 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        A4 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        A5 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        A1 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        A7 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        A8 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        A9 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        A10 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        A6 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        A32 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        A11 = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        A31 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        A13 = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        A14 = new javax.swing.JTextArea();
        jScrollPane16 = new javax.swing.JScrollPane();
        A12 = new javax.swing.JTextArea();
        jScrollPane17 = new javax.swing.JScrollPane();
        A16 = new javax.swing.JTextArea();
        jScrollPane18 = new javax.swing.JScrollPane();
        A17 = new javax.swing.JTextArea();
        jScrollPane19 = new javax.swing.JScrollPane();
        A18 = new javax.swing.JTextArea();
        jScrollPane20 = new javax.swing.JScrollPane();
        A19 = new javax.swing.JTextArea();
        jScrollPane21 = new javax.swing.JScrollPane();
        A15 = new javax.swing.JTextArea();
        jScrollPane22 = new javax.swing.JScrollPane();
        A21 = new javax.swing.JTextArea();
        jScrollPane23 = new javax.swing.JScrollPane();
        A22 = new javax.swing.JTextArea();
        jScrollPane24 = new javax.swing.JScrollPane();
        A23 = new javax.swing.JTextArea();
        jScrollPane25 = new javax.swing.JScrollPane();
        A24 = new javax.swing.JTextArea();
        jScrollPane26 = new javax.swing.JScrollPane();
        A25 = new javax.swing.JTextArea();
        jScrollPane27 = new javax.swing.JScrollPane();
        A26 = new javax.swing.JTextArea();
        jScrollPane28 = new javax.swing.JScrollPane();
        A27 = new javax.swing.JTextArea();
        jScrollPane29 = new javax.swing.JScrollPane();
        A28 = new javax.swing.JTextArea();
        jScrollPane30 = new javax.swing.JScrollPane();
        A29 = new javax.swing.JTextArea();
        jScrollPane31 = new javax.swing.JScrollPane();
        A20 = new javax.swing.JTextArea();
        jScrollPane32 = new javax.swing.JScrollPane();
        A30 = new javax.swing.JTextArea();
        jButton1Play = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldScore = new javax.swing.JTextField();
        jButton2RpllDice = new javax.swing.JButton();
        jLabel3DiceNumber = new javax.swing.JLabel();
        jTextField1Name = new javax.swing.JTextField();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Enter Your Name:");

        jScrollPane1.setBackground(new java.awt.Color(0, 204, 51));

        A2.setBackground(new java.awt.Color(0, 204, 0));
        A2.setColumns(20);
        A2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A2.setForeground(new java.awt.Color(255, 255, 255));
        A2.setRows(5);
        A2.setText("+10");
        jScrollPane1.setViewportView(A2);

        jScrollPane2.setBackground(new java.awt.Color(0, 204, 51));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        A3.setBackground(new java.awt.Color(0, 204, 51));
        A3.setColumns(20);
        A3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A3.setForeground(new java.awt.Color(255, 255, 255));
        A3.setRows(5);
        A3.setText("+10");
        jScrollPane2.setViewportView(A3);

        A4.setBackground(new java.awt.Color(0, 204, 204));
        A4.setColumns(20);
        A4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A4.setForeground(new java.awt.Color(255, 255, 255));
        A4.setRows(5);
        A4.setText("\nEMPTY");
        jScrollPane3.setViewportView(A4);

        A5.setBackground(new java.awt.Color(0, 204, 51));
        A5.setColumns(20);
        A5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A5.setForeground(new java.awt.Color(255, 255, 255));
        A5.setRows(5);
        A5.setText("+10");
        jScrollPane4.setViewportView(A5);

        A1.setBackground(new java.awt.Color(102, 0, 102));
        A1.setColumns(20);
        A1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A1.setForeground(new java.awt.Color(255, 255, 255));
        A1.setText("START");
        A1.setCaretColor(new java.awt.Color(255, 255, 255));
        A1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane5.setViewportView(A1);

        A7.setBackground(new java.awt.Color(255, 153, 0));
        A7.setColumns(20);
        A7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A7.setForeground(new java.awt.Color(255, 255, 255));
        A7.setRows(5);
        A7.setText("TRAP\n");
        jScrollPane6.setViewportView(A7);

        A8.setBackground(new java.awt.Color(0, 204, 204));
        A8.setColumns(20);
        A8.setForeground(new java.awt.Color(255, 255, 255));
        A8.setRows(5);
        A8.setText("EMPTY");
        jScrollPane7.setViewportView(A8);

        A9.setBackground(new java.awt.Color(0, 204, 51));
        A9.setColumns(20);
        A9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A9.setForeground(new java.awt.Color(255, 255, 255));
        A9.setRows(5);
        A9.setText("+10");
        jScrollPane8.setViewportView(A9);

        A10.setBackground(new java.awt.Color(255, 153, 0));
        A10.setColumns(20);
        A10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A10.setForeground(new java.awt.Color(255, 255, 255));
        A10.setRows(5);
        A10.setText("TRAP\n");
        jScrollPane9.setViewportView(A10);

        A6.setBackground(new java.awt.Color(0, 204, 0));
        A6.setColumns(20);
        A6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A6.setForeground(new java.awt.Color(255, 255, 255));
        A6.setRows(5);
        A6.setText("+10");
        jScrollPane10.setViewportView(A6);

        A32.setBackground(new java.awt.Color(102, 0, 102));
        A32.setColumns(20);
        A32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A32.setForeground(new java.awt.Color(255, 255, 255));
        A32.setLineWrap(true);
        A32.setRows(5);
        A32.setText("END");
        jScrollPane11.setViewportView(A32);

        A11.setBackground(new java.awt.Color(0, 204, 204));
        A11.setColumns(20);
        A11.setForeground(new java.awt.Color(255, 255, 255));
        A11.setRows(5);
        A11.setText("EMPTY\n");
        jScrollPane12.setViewportView(A11);

        A31.setBackground(new java.awt.Color(255, 153, 0));
        A31.setColumns(20);
        A31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A31.setForeground(new java.awt.Color(255, 255, 255));
        A31.setRows(5);
        A31.setText("TRAP");
        jScrollPane13.setViewportView(A31);

        A13.setBackground(new java.awt.Color(0, 204, 51));
        A13.setColumns(20);
        A13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A13.setForeground(new java.awt.Color(255, 255, 255));
        A13.setRows(5);
        A13.setText("+10");
        jScrollPane14.setViewportView(A13);

        A14.setBackground(new java.awt.Color(0, 204, 51));
        A14.setColumns(20);
        A14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A14.setForeground(new java.awt.Color(255, 255, 255));
        A14.setRows(5);
        A14.setText("+10");
        jScrollPane15.setViewportView(A14);

        A12.setBackground(new java.awt.Color(255, 102, 0));
        A12.setColumns(20);
        A12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A12.setForeground(new java.awt.Color(255, 255, 255));
        A12.setRows(5);
        A12.setText("TRAP");
        jScrollPane16.setViewportView(A12);

        A16.setBackground(new java.awt.Color(0, 204, 204));
        A16.setColumns(20);
        A16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A16.setForeground(new java.awt.Color(255, 255, 255));
        A16.setRows(5);
        A16.setText("EMPTY");
        jScrollPane17.setViewportView(A16);

        A17.setBackground(new java.awt.Color(255, 102, 0));
        A17.setColumns(20);
        A17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A17.setForeground(new java.awt.Color(255, 255, 255));
        A17.setRows(5);
        A17.setText("TRAP");
        jScrollPane18.setViewportView(A17);

        A18.setBackground(new java.awt.Color(0, 204, 51));
        A18.setColumns(20);
        A18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A18.setForeground(new java.awt.Color(255, 255, 255));
        A18.setRows(5);
        A18.setText("+10");
        jScrollPane19.setViewportView(A18);

        A19.setBackground(new java.awt.Color(0, 204, 51));
        A19.setColumns(20);
        A19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A19.setForeground(new java.awt.Color(255, 255, 255));
        A19.setRows(5);
        A19.setText("+10");
        jScrollPane20.setViewportView(A19);

        A15.setBackground(new java.awt.Color(0, 204, 204));
        A15.setColumns(20);
        A15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        A15.setForeground(new java.awt.Color(255, 255, 255));
        A15.setRows(5);
        A15.setText("EMPTY");
        jScrollPane21.setViewportView(A15);

        A21.setBackground(new java.awt.Color(0, 204, 51));
        A21.setColumns(20);
        A21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A21.setForeground(new java.awt.Color(255, 255, 255));
        A21.setRows(5);
        A21.setText("+10");
        jScrollPane22.setViewportView(A21);

        A22.setBackground(new java.awt.Color(255, 102, 0));
        A22.setColumns(20);
        A22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A22.setForeground(new java.awt.Color(255, 255, 255));
        A22.setRows(5);
        A22.setText("TRAP");
        jScrollPane23.setViewportView(A22);

        A23.setBackground(new java.awt.Color(0, 204, 0));
        A23.setColumns(20);
        A23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A23.setForeground(new java.awt.Color(255, 255, 255));
        A23.setRows(5);
        A23.setText("+10");
        jScrollPane24.setViewportView(A23);

        A24.setBackground(new java.awt.Color(0, 204, 204));
        A24.setColumns(20);
        A24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A24.setForeground(new java.awt.Color(255, 255, 255));
        A24.setRows(5);
        A24.setText("EMPTY");
        jScrollPane25.setViewportView(A24);

        A25.setBackground(new java.awt.Color(255, 102, 0));
        A25.setColumns(20);
        A25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A25.setForeground(new java.awt.Color(255, 255, 255));
        A25.setRows(5);
        A25.setText("TRAP");
        jScrollPane26.setViewportView(A25);

        A26.setBackground(new java.awt.Color(0, 204, 51));
        A26.setColumns(20);
        A26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A26.setForeground(new java.awt.Color(255, 255, 255));
        A26.setRows(5);
        A26.setText("+10");
        jScrollPane27.setViewportView(A26);

        A27.setBackground(new java.awt.Color(0, 204, 51));
        A27.setColumns(20);
        A27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A27.setForeground(new java.awt.Color(255, 255, 255));
        A27.setRows(5);
        A27.setText("+10");
        jScrollPane28.setViewportView(A27);

        A28.setBackground(new java.awt.Color(255, 153, 0));
        A28.setColumns(20);
        A28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A28.setForeground(new java.awt.Color(255, 255, 255));
        A28.setRows(5);
        A28.setText("TRAP");
        jScrollPane29.setViewportView(A28);

        A29.setBackground(new java.awt.Color(0, 204, 204));
        A29.setColumns(20);
        A29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        A29.setForeground(new java.awt.Color(255, 255, 255));
        A29.setRows(5);
        A29.setText("EMPTY");
        jScrollPane30.setViewportView(A29);

        A20.setBackground(new java.awt.Color(255, 102, 0));
        A20.setColumns(20);
        A20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A20.setForeground(new java.awt.Color(255, 255, 255));
        A20.setRows(5);
        A20.setText("TRAP");
        jScrollPane31.setViewportView(A20);

        A30.setBackground(new java.awt.Color(0, 204, 51));
        A30.setColumns(20);
        A30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A30.setForeground(new java.awt.Color(255, 255, 255));
        A30.setRows(5);
        A30.setText("+10");
        jScrollPane32.setViewportView(A30);

        jButton1Play.setBackground(new java.awt.Color(204, 204, 204));
        jButton1Play.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1Play.setForeground(new java.awt.Color(0, 153, 153));
        jButton1Play.setText("PLAY");
        jButton1Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1PlayActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Score:");

        jTextFieldScore.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jButton2RpllDice.setBackground(new java.awt.Color(204, 204, 204));
        jButton2RpllDice.setForeground(new java.awt.Color(153, 0, 0));
        jButton2RpllDice.setText("ROLL DICE");
        jButton2RpllDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2RpllDiceActionPerformed(evt);
            }
        });

        jLabel3DiceNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jTextField1Name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1Name.setForeground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2RpllDice)
                                        .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel3DiceNumber))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane22, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                                .addGap(12, 12, 12)
                                                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                                        .addGap(14, 14, 14)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(12, 12, 12)
                                                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                                .addGap(10, 10, 10)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                                    .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                    .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                                .addGap(32, 32, 32)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(250, 250, 250)))))
                                .addGap(597, 597, 597))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(130, 130, 130)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(155, 155, 155)
                                .addComponent(jButton1Play, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(559, 559, 559)
                                .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(487, 487, 487)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldScore, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(370, 370, 370)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane29, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2RpllDice)
                                    .addComponent(jLabel3DiceNumber)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton1Play)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jScrollPane17, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(jScrollPane18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addComponent(jScrollPane31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                    .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1PlayActionPerformed
        // play buttonu basildiginda eger user bir isim yazmazsa bir hata mesaji ekrana yazdirilacak
        if (jTextField1Name.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter your name");
        } else {
            playerName = jTextField1Name.getText();
            JOptionPane.showMessageDialog(null, "Good luck");
        }
    }//GEN-LAST:event_jButton1PlayActionPerformed

    private void jButton2RpllDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2RpllDiceActionPerformed

        if (jTextField1Name.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter your name");
        } else {
            playerName = jTextField1Name.getText(); // 1 ile 6 random bir sayi uretiyoruz
            int Dice = GenerateRandomNumber();
            jLabel3DiceNumber.setText(String.valueOf(Dice));
            map.Move(Dice);
            textAreas.Move(Dice);

            textAreas.getData().setText("X");

            if (map.getData().equals("+10")) {
                score += 10;
            } else if (map.getData().equals("TRAP")) {
                score -= 5;
            } else if (map.getData().equals("END")) {
                try {
                    BufferedWriter writer = new BufferedWriter(
                            new FileWriter("score.txt", true)
                    );
                    writer.write(jTextField1Name.getText() + ", Level1," + score);

                    writer.newLine();
                    writer.close();
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Error writing to file: " + e.getMessage());
                }

                int choice = JOptionPane.showConfirmDialog(
                        this,
                        "Congrats! You finished the first level.\nDo you want to continue to the second level?",
                        "Level Complete",
                        JOptionPane.YES_NO_OPTION
                );

                if (choice == JOptionPane.YES_OPTION) {
                    YildizKhouliGameSecoundMap x = new YildizKhouliGameSecoundMap();
                    x.setVisible(true);
                    this.dispose();
                } else if (choice == JOptionPane.NO_OPTION) {
                    YildizKhouliMainMenu x = new YildizKhouliMainMenu();
                    x.setVisible(true);
                    this.dispose();
                }

            }
            jTextFieldScore.setText(String.valueOf(score));
        }
    }//GEN-LAST:event_jButton2RpllDiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YildizKhouliGameFirstMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YildizKhouliGameFirstMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YildizKhouliGameFirstMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YildizKhouliGameFirstMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YildizKhouliGameFirstMap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea A1;
    private javax.swing.JTextArea A10;
    private javax.swing.JTextArea A11;
    private javax.swing.JTextArea A12;
    private javax.swing.JTextArea A13;
    private javax.swing.JTextArea A14;
    private javax.swing.JTextArea A15;
    private javax.swing.JTextArea A16;
    private javax.swing.JTextArea A17;
    private javax.swing.JTextArea A18;
    private javax.swing.JTextArea A19;
    private javax.swing.JTextArea A2;
    private javax.swing.JTextArea A20;
    private javax.swing.JTextArea A21;
    private javax.swing.JTextArea A22;
    private javax.swing.JTextArea A23;
    private javax.swing.JTextArea A24;
    private javax.swing.JTextArea A25;
    private javax.swing.JTextArea A26;
    private javax.swing.JTextArea A27;
    private javax.swing.JTextArea A28;
    private javax.swing.JTextArea A29;
    private javax.swing.JTextArea A3;
    private javax.swing.JTextArea A30;
    private javax.swing.JTextArea A31;
    private javax.swing.JTextArea A32;
    private javax.swing.JTextArea A4;
    private javax.swing.JTextArea A5;
    private javax.swing.JTextArea A6;
    private javax.swing.JTextArea A7;
    private javax.swing.JTextArea A8;
    private javax.swing.JTextArea A9;
    private javax.swing.JButton jButton1Play;
    private javax.swing.JButton jButton2RpllDice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3DiceNumber;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField1Name;
    private javax.swing.JTextField jTextFieldScore;
    // End of variables declaration//GEN-END:variables

}
